package rules

import com.ftn.sbnz.model.Home
import com.ftn.sbnz.model.SolarGenerator
import com.ftn.sbnz.model.PowerSource

rule "when solar production exceeds demand, switch to solar"
    when
        $home: Home($consumption: currentConsumption, powerSource == PowerSource.GRID)
        $solar: SolarGenerator(production >= $consumption, currentBatteryCharge > 30.0)
    then
        modify($home){setPowerSource(PowerSource.RESERVES)}
end

