package rules

import com.ftn.sbnz.model.Home
import com.ftn.sbnz.model.SpaceHeater
import com.ftn.sbnz.model.Radiator
import com.ftn.sbnz.model.FloorHeater
import com.ftn.sbnz.model.TemperatureReading

rule "turn on heating if the temperature is 10% lower than the desired temperature"
salience 100
    when
        $tempReading: TemperatureReading($temp: temperature)
        $home: Home(desiredTemp != null, $temp <= desiredTemp * 0.9)
        $spaceHeater: SpaceHeater()
        $radiator: Radiator()
        $floorHeating: FloorHeater()
    then
        modify($spaceHeater){setOn(true)}
        modify($radiator){setOn(true)}
        modify($floorHeating){setOn(true)}
end
