package rules.smartHome

import com.ftn.sbnz.model.Home
import com.ftn.sbnz.model.SolarGenerator
import com.ftn.sbnz.model.HomeProfile

rule "when solar production exceeds demand, swtich to solar"
    when
        $home: Home( $consumption: currentConsumption, profile == HomeProfile.GRID )
        $solar: SolarGenerator( production >= $consumption )
    then
        modify($home){$home.setProfile(HomeProfile.RESERVES)}
end

